# Global replica defaults
api:
  replicaCount: 1
  image:
    repository: "tiangolo/uvicorn-gunicorn-fastapi"
    tag: "python3.11"
  service:
    port: 8000

web:
  replicaCount: 1
  image:
    repository: "nginx"
    tag: "alpine"
  service:
    port: 80
    nodePort: 30080
