# Global replica defaults
api:
  replicaCount: 1
  image:
    repository: "ghcr.io/your-org/minishop-api"
    tag: "latest"
  service:
    port: 8000

web:
  replicaCount: 1
  image:
    repository: "nginx"
    tag: "alpine"
  service:
    port: 80
    nodePort: 30080
